### ISSUE TITLE
Upgrade appcontainer-driver to 1.0.6

### ISSUE THREAD

**Issue by kood1** [FINRAOS/karma-msl#8]
Update plugin to use the latest msl browser client with the following PR included:

https://github.com/FINRAOS/MSL/pull/68

**Comment by kood1** [comment]
@seoj - do you want to make a PR to this project to include the latest appcontainer-driver.min.js?  You should take credit for this update since 1.0.6 includes your changes :-)

We'll need the following changes:
- Add the following file to the lib directory - https://github.com/FINRAOS/MSL/blob/v1.0.6/msl-client-browser/appcontainer-driver.min.js
- Change version number in package.json to 0.0.14
- Modify README.md to say "karma-msl": "~0.0.14"

Once we merge the PR, I can publish to npm.  Thanks!

**Comment by seoj** [comment]
Done, done and done.
Pull request https://github.com/FINRAOS/karma-msl/pull/9 created!
